### ISSUE TITLE
Home Music folder support

### ISSUE THREAD

**Issue by j1nx** [NeonGeckoCom/skill-local_music#3]
Going to give this skill a try in the upcoming week, however as feedback upfront;

Could the "/media" support be extended to also support "~/Music" by default as that is a default Desktop folder on Linux clients and also present within OpenVoiceOS.

**Comment by NeonDaniel** [comment]
Makes sense as a default; I matched the Mycroft Dinkum skill to expect a mounted drive, but I did intend to support multiple paths, so that's a good default location to index
