### ISSUE TITLE
[BUG] Demo music played instead of local music

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/skill-local_music#43]
### Description

mana say-to 'play local music' - displayed the music title on my usb thumbdrive, 
BUT played some (local?) music from somewhere instead.

### Steps to Reproduce

had to update the settings.json file to > > is this another {BUG} report??? < <
```
{
    "__mycroft_skill_firstrun": false,
    "demo_url": "https://2222.us/app/files/neon_music/music.zip",
    "music_dir": "/media/sdb1"
}
```
NOTICE the partition designation o\in the "music_dir" value
** I also deleted the demo_url
then did a "menu/reboot_services" so the change would be include in your meta settings
**
now I can do the mana say-to 'play local music' - I saw my title flash by in the small window at the top of the gui
but it didn't play either of the two choices (both .mp3)

### Relevant Code

settings.json apparently needs the partition info also

### Other Notes

Release 24.5.1 
Mark II / sj201-R6 / usb/SDD for OS / usb-thumbdrive in second port for music
have to use 'mana say-to' as Neon doesn't detect? my vocal input
'
sent troubleshooting package, Neon didn't recognize my email address in the ngi_user_info.yaml
[logs.5_1OS.tar.gz](https://github.com/NeonGeckoCom/skill-local_music/files/15299659/logs.5_1OS.tar.gz)

**Comment by Olzeke51** [comment]
OOPs - what I saw was the .mp3 in my ~/Music  dir - - that I had to manually create and do a root transfer from sdb1 to it
hmmm - permissions /  nafaict
```
(venv) neon@neon:~/Music$ ls -l
total 61364
-rw-r--r-- 1 root root 62835506 Mar  4  2018 ProgMusic_0010.mp3
```

**Comment by NeonDaniel** [comment]
> OOPs - what I saw was the .mp3 in my ~/Music dir - - that I had to manually create and do a root transfer from sdb1 to it hmmm - permissions / nafaict
> 
> ```
> (venv) neon@neon:~/Music$ ls -l
> total 61364
> -rw-r--r-- 1 root root 62835506 Mar  4  2018 ProgMusic_0010.mp3
> ```

I recall discussing this in Matrix.. Did your music playback end up working or is this still an issue?

**Comment by Olzeke51** [comment]
Still an issue - only worse in beta .5.16b12
Neon says "I don't understand'  and gui shows my mana say-to script
edit: beta 5.16.b12 can't understand 'play local music' OR
 mana say-to 'play music /home/neon/Music/[mello.mp](http://mello.mp/)3'
edit:
```(venv) neon@neon:~/.config/neon/skills/skill-local_music.neongeckocom$ cat settings.json
{
    "__mycroft_skill_firstrun": false,
    "music_dir": "/home/neon/Music"
}(venv) neon@neon:~/.config/neon/skills/skill-local_music.neongeckocom$ 
```

**Comment by Olzeke51** [comment]
No, not at all!  beta .5.16b2 (was an update from .5.16b1)
I was in between your posting @
https://github.com/NeonGeckoCom/neon-os/releases

**Comment by Olzeke51** [comment]
No, not at all!
No, not at all!  beta .5.16b2 (was an update from .5.16b1)
I was in between your posting

**Comment by NeonDaniel** [comment]
> Still an issue - only worse in beta .5.16b12 Neon says "I don't understand' and gui shows my mana say-to script edit: beta 5.16.b12 can't understand 'play local music' OR mana say-to 'play music /home/neon/Music/[mello.mp](http://mello.mp/)3' edit:
> 
> ```
> {
>     "__mycroft_skill_firstrun": false,
>     "music_dir": "/home/neon/Music"
> }(venv) neon@neon:~/.config/neon/skills/skill-local_music.neongeckocom$ 
> ```

If you ask "play mello" does it play? I'll check out the "play local music" intent since that should pick non-demo music from this skill if there's any other local music available

**Comment by Olzeke51** [comment]
play mello = 'I don't understand" with my text on the screen also,
don't even get the little window scanning for music

**Comment by NeonDaniel** [comment]
New issue causing the "I don't understand" response.. I raised this in [OVOS Plugin Manager](https://github.com/OpenVoiceOS/ovos-plugin-manager/issues/229) but it appears a recent alpha release there broke the media playback plugin. I'll get the dependencies fixed up in Neon and continue testing the original issue here.

**Comment by NeonDaniel** [comment]
@Olzeke51 if you have a chance to test,
```shell
pip install --upgrade --pre neon-audio
pip install --no-deps --force-reinstall git+https://github.com/neongeckocom/skill-local_music@FEAT_MatchNonDemoLocalMusic
sudo systemctl restart neon
```
should get music working again and make it so "play local music" finds your music without the demo tracks. The audio fix will make it into a release later tonight after I get [this PR](https://github.com/NeonGeckoCom/NeonCore/pull/677).

I'll wait for you or someone else to validate the music skill changes before I merge that and close this issue.

**Comment by Olzeke51** [comment]
ran scripts 
"play local music' {mana}
picked and played the last song in my Music folder {per alpha listing}
did update to 17b15
(venv) neon@neon:~$ mana say-to 'play local mello.mp3'
[this worked once a long time ago]
jumped to a Classical song !! in the neon repository
so I stopped via gui
(venv) neon@neon:~$ mana say-to 'play local music'
this now played a Country song from the neon repository
(venv) neon@neon:~$ mana say-to 'stop'
doing a 'reboot services' via menu pulldown
then
(venv) neon@neon:~$ mana say-to 'play local music'
	it showed my music in the search window of the gui
	BUT it played a random song from the neon repository
	
** reran scripts- it played my first song via 'play local music'
did a second 'play local music' and it picked up the second song in my Music directory

**Comment by Olzeke51** [comment]
ran scripts
"play local music' {mana}
picked and played the last song in my Music folder {per alpha listing}
did update to 17b15
(venv) ***@***.***:~$ mana say-to 'play local mello.mp3'
[this worked once a long time ago]
jumped to a Classical song !! in the neon repository
so I stopped via gui
(venv) ***@***.***:~$ mana say-to 'play local music'
this now played a Country song from the neon repository
(venv) ***@***.***:~$ mana say-to 'stop'
doing a 'reboot services' via menu pulldown
then
(venv) ***@***.***:~$ mana say-to 'play local music'
it showed my music in the search window of the gui
BUT it played a random song from the neon repository

** reran scripts- it played my first song via 'play local music'
did a second 'play local music' and it picked up the second song in my
Music directory

**Comment by Olzeke51** [comment]
gonna be working until 4PM - east coast.
I am not expecting you to work on this - programmers need a life too !!!😄

**Comment by Olzeke51** [comment]
did a menu/shutdown/shutdown and it all came up good - played local music !!!!!!!!!😘

**Comment by Olzeke51** [comment]
basic testing of the 24.5.17b15 beta is working.  Would consider the main issue closed
